### ISSUE TITLE
Проблема с отображением текста кнопки управления избранным на странице ивента

### ISSUE THREAD

**Issue by leksidev** [openworld-community/ows-events-mobile#108]
В эмуляторе у меня это выглядит так: 
![Screenshot_20230704_140954](https://github.com/openworld-community/ows-events-mobile/assets/96407924/ddfcda4a-93da-4d8d-9088-ec7c7fc12537)

Текста куда-то уезжает из видимой области.

**Comment by ArkadiiIL** [comment]
Там еще если слишком большой текст выдает ошибку
