### ISSUE TITLE
Добавить обновление списка событий при свайпе вниз

### ISSUE THREAD

**Issue by MariannaKhanina** [openworld-community/ows-events-mobile#44]
Если что можно использовать вот этот https://pub.dev/packages/custom_refresh_indicator

**Comment by MariannaKhanina** [comment]
- [ ] добавить рефреш индикатор
- [ ] добавить обновление списка на onRefresh

**Comment by ArkadiiIL** [comment]
Я добавил простой индикатор, но работает он только на мобилке
