### ISSUE TITLE
Поменять url API на актуальный. Разобраться с генерацией апи и сгенерировать новую версию

### ISSUE THREAD

**Issue by MariannaKhanina** [openworld-community/ows-events-mobile#59]
- [x] добавить эндпоинт для получения списка Городов
- [x] добавить эндпоинт для получения списка Стран
- [ ] добавить эндпоинт для поиска

**Comment by leksidev** [comment]
апи поменяла в багфиксе, продовский будем убирать и выносить отдельно. Занимаюсь переработкой сборки данных, потому что мы забирали не всё
