### ISSUE TITLE
Отобразить события из API

### ISSUE THREAD

**Issue by IlyaGulya** [openworld-community/ows-events-mobile#6]
Так как у нас теперь есть карточка события, можно отрендерить список событий который мы получаем с сервера.
Код получающий список уже имеется в main.dart в функции main. 
Можно пока тупо брать этот загруженный на старте приложения список и рендерить его. 
Потом сделаем красиво, а пока и так норм.

**Comment by ArkadiiIL** [comment]
А events через роутер передавать?
