### ISSUE TITLE
Реализовать обрезку текста в описании ивента в айтемс ивент листе

### ISSUE THREAD

**Issue by leksidev** [openworld-community/ows-events-mobile#74]
Он может быть любой длины, но лучше или вообще убрать его отображение в ленте и оставить только в карточке ивента, или обрезать до пары строчек

**Comment by MariannaKhanina** [comment]
Надо в доке по матиреалу посмотреть, что там есть для красивого обрезания и скрытия текста. Как ещё один вариант - текст можно сворачивать/разворачивать
